library(readr)
library(ggplot2)
library(tidyverse)

# Load data
df <- readr::read_csv("data-data.csv")

# Create plot
p <- ggplot2::ggplot(df, ggplot2::aes(x = year, y = data_generated)) +
    ggplot2::geom_line() +
    ggplot2::geom_point() +
    ggplot2::labs(
        title = "Data Generated by Year",
        x = "Year",
        y = "Data Generated (zettabytes)"
    ) +
    ggplot2::theme_minimal()

print(p)
